@extends('layouts.weblayout')
@section('title', 'Terms & Conditions')
@section('customstyles')
    
@endsection


@section('main-content')
    <!-- hero area start -->
    <section class="all-page-hero about-page">
            <div class="page-content container">
                     <span class="about-active"> Terms & Conditions</span>
                 </div>
         </section>
     
         <!-- hero area end -->
         <!-- Our Vision area start -->
         <section class="popular-courses section-padding vision-area">
             <div class="container">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="section-heading ">
                             <h2>TERMS OF USE</h2>
                             <p>
                                IMPORTANT! THESE TERMS OF USE GOVERN YOUR USE OF THIS SITE, WHICH IS PROVIDED BY OUR COMPANY. BY ACCESSING THIS SITE, YOU ARE INDICATING YOUR ACKNOWLEDGMENT AND ACCEPTANCE OF THESE TERMS OF USE. THESE TERMS OF USE ARE SUBJECT TO CHANGE BY OUR COMPANY AT ANY TIME IN ITS DISCRETION. YOUR USE OF THIS SITE AFTER SUCH CHANGES ARE IMPLEMENTED CONSTITUTES YOUR ACKNOWLEDGMENT AND ACCEPTANCE OF THE CHANGES. PLEASE CONSULT THESE TERMS OF USE REGULARLY.</p>
                                <p>Access To This Site<br>
                                You agree to use this site only for the lawful purposes described in more detail in the “Restrictions on Use” section below. You agree not to take any action that might compromise the security of the site, render the site inaccessible to others or otherwise cause damage to the site or the Content.</p>
                                <p>You agree not to add to, subtract from, or otherwise modify the Content, or to attempt to access any Content that is not intended for you. You agree not to use the Site in any manner that might interfere with the rights of third parties. To access this site or some of the resources it has to offer, you may be asked to provide certain registration details or other information. It is a condition of your use of this site that all the information you provide on this site will be correct, current, and complete. If our Company believes the information you provide is not correct, current, or complete, we have the right to refuse you access to this site or any of its resources, and to terminate or suspend your access at any time, without notice.</p>
                                <p>Restrictions On Use<br>
                                This site is provided solely for non-commercial, personal use, and/or so that you may learn about ourCompany and the services we provide . You may not use this site for any other purpose, including any commercial purpose, without our Company’s express prior written consent. For example, you may not (and may not authorize any other party to) (i) co-brand this site, or (ii) frame this site, or (iii) hyper-link to this site, without the express prior written permission of an authorized representative of our Company. For purposes of these Terms of Use, “co-branding” means to display a name, logo, trademark, or other means of attribution or identification of any party in such a manner as is reasonably likely to give a user the impression that such other party has the right to display, publish, or distribute this site or Content accessible within this site. You agree to cooperate with our Company in causing any unauthorized co-branding, framing or hyper-linking immediately to cease.</p>
                                <p>Proprietary Information</p>
                                <p>Trademarks<br>
                                The material and Content accessible from this site, and any other World Wide Web site owned, operated, licensed, or controlled by our Company is the proprietary information of our Company or the party that provided the Content to our Company, and our Company or the party that provided the Content to our Company retains all right, title, and interest in the Content. Accordingly, the Content may not be copied, distributed, republished, uploaded, posted, or transmitted in any way without the prior written consent of our Company, or unless authorized in writing elsewhere on our site, except that you may print out a copy of the Content solely for your personal use. You are prohibited from using any of the marks or logos appearing throughout the site without the express written permission of our Company.</p>
                                <p>Copyrights<br>
                                This site and its Content are protected by U.S. and/or foreign copyright laws, and belong to theCompany or its partners, affiliates, contributors or third parties. The copyrights for the Content are owned by the Company or other copyright owners who have authorized their use on this site. You may download and reprint Content for non-commercial, non-public, personal use only (If you are browsing this site as an employee or member of any business or organization, you may download and reprint Content only for educational or other non-commercial purposes within your business or organization, except as otherwise permitted by the Company, for example in certain password-restricted areas of the site). You may not manipulate or alter in any way images or other Content on the site.</p>
                                <p>Hyper-Links<br>
                                This site may be hyper-linked to other sites which are not maintained by, or related to, our Company. The inclusion of any hyper-link to a third-party site does not imply endorsement, sponsorship or recommendation by our Company of that site. Hyper-links to such sites are provided as a service to users and are not sponsored by or affiliated with this site or our Company. Our Company has not reviewed any or all of such sites and is not responsible for the content of those sites. Our Company also makes no representations about the availability of hyper-linked sites. Hyper-links are to be accessed at the user’s own risk, and our Company makes no representations or warranties about the content, completeness or accuracy of these hyper-links or the sites hyper-linked to this site. If you hyper-link to a site, please be aware that you willl leave our Company’s web site and will become subject to the rules and conditions of the linked site(s). We recommend that you make yourself aware of the Terms of Use of any sites you link to from our Company’s site.</p>
                                <p>Submissions<br>
                                You hereby grant to our Company the royalty-free, perpetual, irrevocable, worldwide, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform, and display all content, remarks, suggestions, ideas, graphics, or other information communicated to our Company through this site (together, hereinafter known as the “Submission”), and to incorporate any Submission in other works in any form, media, or technology now known or later developed. Our Company will not be required to treat any Submission as confidential, and may use any Submission in its business (including without limitation, for products or advertising) without incurring any liability for royalties or any other consideration of any kind, and will not incur any liability as a result of any similarities that may appear in future Company operations. By making a Submission, you are guaranteeing to us that you have the legal right to post the content in the Submission and that it will not violate any law or the rights of any person or entity.</p>
                                <p>Our Company will treat any personal information that you submit through this site in accordance with its Privacy Policy as set forth on this site.</p>
                                <p>Child Safety<br>
                                Protecting the online privacy of children is especially important to us, and those under the age of 13 are protected by federal law. For that reason, our Company does not knowingly permit children under the age of 13 to become registered members of our sites, or to buy goods and services on our sites, without verifiable parental consent. Our Company does not knowingly collect or solicit personal information about children under 13, except with their parent’s express consent.</p>
                                <p>If we ever include children under the age of 13 as part of our intended site audience, those specific web pages will, in accordance with the provisions of the Children’s Online Privacy Protection Act (COPPA), be clearly identified and provide an explicit privacy notice; and we will provide processes to obtain parental approval, provide access to information and allow parents to request removal of their children’s personal information.</p>
                                <p>Downloading Material<br>
                                You understand that our Company cannot and does not guarantee or warrant that files available for downloading from the Internet will be free of viruses, worms, Trojan horses or other code that may manifest contaminating or destructive properties. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for accuracy of data input and output, and for maintaining a means external to this site for the reconstruction of any lost data. OurCompany does not assume any responsibility or risk for your use of the Internet.</p>
                                <p>Disclaimer<br>
                                THE COMPANY MAKES NO EXPRESS OR IMPLIED WARRANTIES, REPRESENTATIONS OR ENDORSEMENTS WHATSOEVER WITH RESPECT TO THE SITE, THE SERVICE OR THE CONTENT. THE COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT, WITH REGARD TO THE SITE, THE SERVICE, THE CONTENT, AND ANY PRODUCT OR SERVICE FURNISHED OR TO BE FURNISHED VIA THE SITE. THE COMPANY DOES NOT WARRANT THAT THE FUNCTIONS PERFORMED BY THE SITE OR THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE, OR THAT DEFECTS IN THE SITE OR THE SERVICE WILL BE CORRECTED. THE COMPANY DOES NOT WARRANT THE ACCURACY OR COMPLETENESS OF THE CONTENT, OR THAT ANY ERRORS IN THE CONTENT WILL BE CORRECTED. THE SITE, THE SERVICE AND THE CONTENT ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS.</p>
                                <p>Limitation On Liability<br>
                                COMPANY, ITS SUBSIDIARIES, AFFILIATES, LICENSORS, SERVICE PROVIDERS, CONTENT PROVIDERS, EMPLOYEES, AGENTS, OFFICERS, AND DIRECTORS WILL NOT BE LIABLE FOR ANY INCIDENTAL, DIRECT, INDIRECT, PUNITIVE, ACTUAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR OTHER DAMAGES, INCLUDING LOSS OF REVENUE OR INCOME, PAIN AND SUFFERING, EMOTIONAL DISTRESS, OR SIMILAR DAMAGES, EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL THE COLLECTIVE LIABILITY OF COMPANY AND ITS SUBSIDIARIES, AFFILIATES, LICENSORS, SERVICE PROVIDERS, CONTENT PROVIDERS, EMPLOYEES, AGENTS, OFFICERS, AND DIRECTORS, TO ANY PARTY (REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT, OR OTHERWISE) EXCEED THE GREATER OF $100 OR THE AMOUNT YOU HAVE PAID TO COMPANY FOR THE APPLICABLE CONTENT, PRODUCT OR SERVICE OUT OF WHICH LIABILITY AROSE.</p>
                                <p>Indemnity<br>
                                You will indemnify and hold Company, its subsidiaries, affiliates, licensors, content providers, service providers, employees, agents, officers, directors, and contractors (hereinafter known as the “Indemnified Parties”) harmless from any breach of these Terms of Use by you, including any use of Content other than as expressly authorized in these Terms of Use. You agree that the Indemnified Parties will have no liability in connection with any such breach or unauthorized use, and you agree to indemnify any and all resulting loss, damages, judgments, awards, costs, expenses, and attorney’s fees of the Indemnified Parties in connection therewith. You will also indemnify and hold the Indemnified Parties harmless from and against any claims brought by third parties arising out of your use of the information accessed from this site.</p>
                                <p>Information You Provide<br>
                                You may not post, send, submit, publish, or transmit in connection with this site any material that: you do not have the right to post, including proprietary material of any third party; advocates illegal activity or discusses an intent to commit an illegal act; is vulgar, obscene, pornographic, or indecent; does not pertain directly to this site;<br>
                                threatens or abuses others, libels, defames, invades privacy, stalks, is obscene, pornographic, racist, abusive, harassing, threatening or offensive;<br>
                                seeks to exploit or harm children by exposing them to inappropriate content, asking for personally identifiable details or otherwise;<br>
                                infringes any intellectual property or other right of any entity or person, including violating anyone’s copyrights or trademarks or their rights of publicity; violates any law or may be considered to violate any law;<br>
                                impersonates or misrepresents your connection to any other entity or person or otherwise manipulates headers or identifiers to disguise the origin of the content; advertises any commercial endeavor (e.g., offering for sale products or services) or otherwise engages in any commercial activity (e.g., conducting raffles or contests, displaying sponsorship banners, and/or soliciting goods or services) except as may be specifically authorized on this site; solicits funds, advertisers or sponsors; includes programs which contain viruses, worms and/or Trojan horses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications; disrupts the normal flow of dialogue, causes a screen to scroll faster than other users are able to type, or otherwise act in a way which affects the ability of other people to engage in real time activities via this site; includes MP3 format files; amounts to a ‘pyramid’ or similar scheme; disobeys any policy or regulations established from time to time regarding use of this site or any networks connected to this site; or contains hyper-links to other sites that contain content that falls within the descriptions set forth above.</p>
                                <p>Although under no obligation to do so, our Company reserves the right to monitor use of this site to determine compliance with these Terms of Use, as well as the right to remove or refuse any information for any reason. Notwithstanding these rights, you remain solely responsible for the content of your Submissions. You acknowledge and agree that neither Company nor any third party that provides Content to Company will assume or have any liability for any action or inaction by Company or such third party with respect to any Submission.</p>
                                <p>Security<br>
                                Any passwords used for this site are for individual use only. You will be responsible for the security of your password (if any). Company will be entitled to monitor your password and, at its discretion, require you to change it. If you use a password that Company considers insecure, Company will be entitled to require the password to be changed and/or terminate your account.</p>
                                <p>You are prohibited from using any services or facilities provided in connection with this site to compromise security or tamper with system resources and/or accounts. The use or distribution of tools designed for compromising security (e.g., password guessing programs, cracking tools or network probing tools) is strictly prohibited. If you become involved in any violation of system security, Company reserves the right to release your details to system administrators at other sites in order to assist them in resolving security incidents. Company reserves the right to investigate suspected violations of these Terms of Use.</p>
                                <p>Company reserves the right to fully cooperate with any law enforcement authorities or court order requesting or directing Company to disclose the identity of anyone posting any e-mail messages, or publishing or otherwise making available any materials that are believed to violate these Terms of Use.</p>
                                <p>BY ACCEPTING THIS AGREEMENT YOU WAIVE AND HOLD HARMLESS COMPANY FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY COMPANY DURING OR AS A RESULT OF ITS INVESTIGATIONS AND/OR FROM ANY ACTIONS TAKEN AS A CONSEQUENCE OF INVESTIGATIONS BY EITHER THE COMPANY OR LAW ENFORCEMENT AUTHORITIES.</p>
                                <p>Claims of Copyright Infringement<br>
                                Pursuant to Title 17, United States Code, Section 512(c)(2), notifications of claimed copyright infringement should be sent to Service Provider’s Designated Agent.</p>
                                <p>Miscellaneous<br>
                                These Terms of Use will be governed and interpreted pursuant to the laws of Oregon, United States of America, notwithstanding any principles of conflicts of law. You specifically consent to personal jurisdiction in Oregon in connection with any dispute between you and Company arising out of these Terms of Use or pertaining to the subject matter hereof. The parties to these Terms of Use each agree that the exclusive venue for any dispute between the parties arising out of these Terms of Use or pertaining to the subject matter of these Terms of Use will be in the state and/or federal courts in Deschutes County, Oregon. If any part of these Terms of Use is unlawful, void or unenforceable, that part will be deemed severable and will not affect the validity and enforceability of any remaining provisions.</p>
                                <p>These Terms of Use constitute the entire agreement among the parties relating to this subject matter. Notwithstanding the foregoing, any additional terms and conditions on this site will govern the items to which they pertain. Company may revise these Terms of Use at any time by updating this posting.</p>
                         </div>
                     </div>
                 </div>
             </div>
         </section>
         <!-- vision area end -->
@endsection
    
@section('customjs')
    
@endsection
